### PR TITLE
Fix misunderstandable documentation about using Attributes

### PR DESCRIPTION
**Pull request by welcoMattic**

### CODE REVIEW

**Review by garak — CHANGES_REQUESTED** [review]
I appreciate the effort to make docs clearer, anyway I don't think that mentioning the path of configuration file could be better understood: the configuration can be located elsewhere and the only relevant part is the configuration path

**Comment by welcoMattic** [comment]
As this file path is the one provided by the Flex recipe, I think it is the most relevant, don't you think?

**Comment by garak** [comment]
> As this file path is the one provided by the Flex recipe, I think it is the most relevant, don't you think?

We need to stay abstract, we're not sure that everyone is using flex.
So, OK for mentioning the path, but only as a possibility

**Comment by welcoMattic** [comment]
@garak fixed ;) thanks for your review

**Review by garak — APPROVED** [review]

**Pull request merged**
