### PR TITLE
Fix default filename suffix usage

### PR DESCRIPTION
**Pull request by Restless-ET**

### CODE REVIEW

**Comment by K-Phoen** [comment]
Thanks for your contribution!

A unit test for this could be nice. Can you write it?
I'll write one before merging if you can't.

**Comment by Restless-ET** [comment]
Added a unit test for a custom filename suffix.

**Comment by K-Phoen** [comment]
:heart:

**Comment by Restless-ET** [comment]
:smile: 

BTW, for when are you planning a new tag release?

**Comment by K-Phoen** [comment]
There are two PR and a few issues to review before that but it should be soon (less than a week).

**Pull request merged**
