### PR TITLE
Update UploadHandler.php

### PR DESCRIPTION
**Pull request by Big-Shark**
Doesn't matter this is upload file, or file, we need just save
Example
```
$filePath = '/tmp/'.uniqid();
file_put_contents($filePath, file_get_contents('https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_120x44dp.png'));
$entity->setImageFile(new File($filePath));
```

### CODE REVIEW

**Comment by garak** [comment]
Can't you just use `new Uploaded file()`?

**Comment by Big-Shark** [comment]
> Can't you just use `new Uploaded file()`?

No, because UploadedFile use php function is_uploaded_file(), and I receive validation error.
P.S. Yes, I can use 5th parameters in UploadedFile constructor, but this is look like a dirty.

**Comment by garak** [comment]
It looks like you already solved your problem

**Comment by Big-Shark** [comment]
> It looks like you already solved your problem

yes, but I think I used dirty hack, and I think this PR is better for all. If you have opposite opinion, please write me answer and close this PR.

**Pull request closed without merging**
