### PR TITLE
make gaufrette's metadata work

### PR DESCRIPTION
**Pull request by dswbx**
make gaufrette's metadata work by creating Gaufrette\File and set metadata there

### CODE REVIEW

**Comment by garak** [comment]
@RSSfeed can you tell something more about this PR?

**Comment by RSSfeed** [comment]
It's been a long time, but as I remember, without this changes, files stored via gaufrette in amazon s3 won't get the correct metadata. E.g. a jpg got mime-type (as far as I remember) "application/octet-stream" instead of "image/jpeg". Without having the correct mime-type the browser won't behave as expected.

With my pull request changes in place the metadata is being added correctly.

**Comment by Koc** [comment]
@RSSfeed can you add test that confirm fix and prevent regression in future?

**Comment by garak** [comment]
@RSSfeed did you take a look to #163?

**Comment by OJezu** [comment]
What is preventing this PR from being merged?

**Comment by garak** [comment]
* This branch has conflicts that must be resolved
* Missing tests
* Awaiting feedback about another possible related issue

**Comment by OJezu** [comment]
This does not fix #163, as when setting metadata in Gaufrette File, Gaufrette first tries to save metadata, and then the file itself. See KnpLabs/Gaufrette#537

Upon closer inspection I don't know if this PR actually changes anything, as 
```
$gaufretteFile = new File($path, $filesystem);
$gaufretteFile->setContent(file_get_contents($file->getPathname()), array('contentType' => $file->getMimeType()));
```

Underneath calls the same `$filesystem->getAdapter()->setMetadata` and `$filesystem->getAdapter()->write`. Workaround for Gaufrette issues would be to write file first, and then setMetadata. If KnpLabs/Gaufrette#537 is fixed, then 
```
$gaufretteFile = new File($path, $filesystem);
$gaufretteFile->setContent(file_get_contents($file->getPathname()), array('contentType' => $file->getMimeType());
```
Could be done no matter if adapter supports metadata or not, and I guess that would be the best solution. It should be up to Gaufrette to save metadata along with file in most atomic way.

**Comment by garak** [comment]
So, what we can do here is waiting for Gaufrette feedback, then close this PR (that looks too old) and open a new one.

**Comment by OJezu** [comment]
Without Gaufrette feedback, Uploader can save file first, then metadata at risk of file being saved without metadata. Or retry saving metadata after file upload, if it failed before. Those are options to consider, if Gaufrette is not fixed.

I looked into fixing Gaufrette myself, but after seeing code I put it off - there is no way to do it there without risking some (internal) BC changes. I will see how KnpLabs/Gaufrette#537 goes.

**Comment by garak** [comment]
Closing because it's too old and without any feedback

**Pull request closed without merging**
