### PR TITLE
keep mapping in sync with annotations doc

### PR DESCRIPTION
**Pull request by robertfausk**
see https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/usage.md#step-2-link-the-upload-mapping-to-an-entity

### CODE REVIEW

**Comment by garak** [comment]
Should we correct XML mapping too?

**Comment by garak** [comment]
@robertfausk can you add a commit with a fix for XML mapping?

**Comment by robertfausk** [comment]
Yep. I'll see if I find some time this week.

**Comment by garak** [comment]
bump!

**Comment by phpeek** [comment]
ping @robertfausk ;)

**Comment by garak** [comment]
I'm afraid I'll need to reject this PR for missing feedback

**Comment by robertfausk** [comment]
Sorry for the very very long delay.
I looked over xml mapping and in all other docs. I also found some mismatches in usage and known issues and changed them.
Hope you are fine with this. If not: Give me a sign.

**Comment by garak** [comment]
Can you squash your commits, excluding merge? Thanks

**Comment by garak** [comment]
@robertfausk any news?

**Pull request closed without merging**
