### PR TITLE
Allow installing Symfony 4 components

### PR DESCRIPTION
**Pull request by javiereguiluz**

### CODE REVIEW

**Comment by garak** [comment]
I guess that we can't merge this until we solve #788

**Comment by javiereguiluz** [comment]
That's correct! I'm going to test it more and see if I find other deprecations. Thanks!

**Comment by weaverryan** [comment]
Btw, here is how this is handled in other bundles :)

https://github.com/doctrine/DoctrineBundle/blob/8b462d952fbd386637a85d642d242a16891e0d32/DependencyInjection/DoctrineExtension.php#L833-L836

**Comment by garak** [comment]
Sorry I had to slightly change the "suggest" area if composer.json, can you solve conflicts please?

**Comment by garak** [comment]
Thanks!

**Pull request merged**
