### PR TITLE
Upgrade jms/metadata to 2.6.1

### PR DESCRIPTION
**Pull request by goetas**
Add support for https://github.com/schmittjoh/metadata/pull/107

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@garak Currently jms/metadata 2.6 is not supported, and there is no conflict on the composer.json so this PR is kinda important if you have time to take a look.

**Comment by garak** [comment]
> @garak Currently jms/metadata 2.6 is not supported, and there is no conflict on the composer.json so this PR is kinda important if you have time to take a look.

Can you elaborate? Our current constraint is `"jms/metadata": "^1.7 || ^2.4"`, so it looks like 2.6.1 is actually supported

**Comment by VincentLanglet** [comment]
> Can you elaborate? Our current constraint is `"jms/metadata": "^1.7 || ^2.4"`, so it looks like 2.6.1 is actually supported

I recently bumped my vendor and seems like that when the jms/metadata is bumped to 2.6+ VichUploader does not work anymore. I assume some BC-break have been introduce to jms/metadata because this PR need to make some change to the serialize/unserialize method in order to works with a 2.6+ version.

**Comment by garak** [comment]
I can only see upgrade information about 2.2 -> 2.3, how can it affect us?
Did jms/metadata break on minor/patch version?

**Comment by garak** [comment]
Moreover, I see [here](https://github.com/schmittjoh/metadata/pull/107) that change is needed only "if you plan to upgrade to the upcoming 3.0 version"

**Comment by goetas** [comment]
2.6 is fully backward compatible, no need to upgrade asap. the the only reason to do it is to be ready to the 3.0 that will drop the `Serializable` interface

**Comment by garak** [comment]
> 2.6 is fully backward compatible, no need to upgrade asap. the the only reason to do it is to be ready to the 3.0 that will drop the `Serializable` interface

I don't get the point of this PR, then

**Comment by goetas** [comment]
if you merge this, when jms/metadata 3.0 will be released, then only thing you will need to do is to add the `^3.0` in the composer.json

**Comment by VincentLanglet** [comment]
That's weird, I need to try again, but the last time I tried to update I got an issue with jms/metadata and vich uploader and only solve the situation by adding a conflict `"jms/metadata": ">= 2.6.0",`. I'll try again soon.

**Comment by garak** [comment]
> if you merge this, when jms/metadata 3.0 will be released, then only thing you will need to do is to add the `^3.0` in the composer.json

So I guess you can close it, and propose a new one when 3.0 will be available

**Comment by goetas** [comment]
>So I guess you can close it, and propose a new one when 3.0 will be available

i'm good with it :+1: 

@VincentLanglet 

>That's weird, I need to try again, but the last time I tried to update I got an issue with jms/metadata and vich uploader and only solve the situation by adding a conflict "jms/metadata": ">= 2.6.0",. I'll try again soon.

There was a bug in 2.6.0 that was fixed few hours after in 2.6.1

**Pull request closed without merging**
