### PR TITLE
Add "delete_callback" option to form types.

### PR DESCRIPTION
**Pull request by Koc**
Do we need cover this with test?

### CODE REVIEW

**Comment by garak** [comment]
Everything needs to be covered with tests

**Comment by kimwue** [comment]
Would like this feature.

**Comment by Koc** [comment]
@kimwue nice to see anybody else who has similar problems like me :). Will try finish this PR soon.

**Comment by garak** [comment]
I'm about to close this, since it's a bit old.
Also, can't you just use a listener to reach the same goal?

**Comment by Koc** [comment]
This PR is not relevant anymore

**Pull request closed without merging**
