### PR TITLE
Make symfony/form a suggestion

### LINKED ISSUE #1201: Suggest symfony/form instead of requiring it
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | maybe

#### Summary

It would be good if this package did not have a hard dependency on `symfony/form`. A [suggestion](https://getcomposer.org/doc/04-schema.md#suggest) could be used instead.

Background: not every user of this package will use Symfony forms. The fact that there is an option to disable the Symfony form integration (`vich_uploader.form`) indicates that this was already kept in mind. An example without Symfony forms is [API platform](https://api-platform.com/docs/core/file-upload/).

Changing this could be a slightly breaking change if projects don't explicitly require `symfony/form`. Then again if projects really use Symfony forms then this is very unlikely. Also the integration option `vich_uploader.form` should then probably be disabled by default.

### PR DESCRIPTION
**Pull request by mbrodala**
Fixes #1201

### CODE REVIEW

**Review by garak — CHANGES_REQUESTED** [review]
I guess that if you remove a dependency, if you need to add it as dev-dependency then

**Comment by mbrodala** [comment]
Yes, obviously. :facepalm: Fixed now.

**Review by garak — CHANGES_REQUESTED** [review]
You can ignore failure on phpstan, it's a bug (not depending on us)
Anyway, we still need to:
1) document this change in UPGRADE.md
2) document the need for form component in types documentation

**Comment by mbrodala** [comment]
Alright, did that now.

**Review by garak — APPROVED** [review]

**Comment by garak** [comment]
Thank you @mbrodala !

**Pull request merged**
