### PR TITLE
Use asset function in form template

### PR DESCRIPTION
**Pull request by matthieumota**
I take conversation from #657, I've closed PR because no more link with my fork (I think my fork was deleted at instant, it indicate ["unknow repository"](https://github.com/isaacs/github/issues/168)). No problems, I simply reopen that PR here :) @garak Sorry for response time, but I was busy. I can try to fix conflicts from this PR.

### CODE REVIEW

**Comment by matthieumota** [comment]
Hi @garak I've resolved conflicts, PR is always consistent for you ? Else, you can close it I think.

**Comment by garak** [comment]
I see that in discussion of old PR I asked for a new option to add, so we can ensure BC

**Comment by garak** [comment]
Moreover, you need to require-dev (and suggest) `symfony/asset`, see failing tests in travis

**Comment by matthieumota** [comment]
@garak Ok for me, I've added option to type.

**Comment by garak** [comment]
Thank you @matthieumota

**Pull request merged**
