### PR TITLE
Make resolving of paths optional for delete link in VichFileType

### PR DESCRIPTION
**Pull request by MrNicodemuz**
My staging server does not have all the files always on the server itself, thus making most of my forms not render at all.

### CODE REVIEW

**Comment by MrNicodemuz** [comment]
@dustin10, any feedback? :)

**Comment by K-Phoen** [comment]
Introducing a new option in the form type to solve a case of missing fixtures in a staging environment seems a bit overkill.

`resolvePath` is used to determine if a file has been uploaded but it checks that the file is present in the filesystem, hence your issue. Another solution would be to use `resolveUri` as it does not check the presence of the file (if I remember correctly).

**Comment by MrNicodemuz** [comment]
@K-Phoen: Thanks for your valuable feedback. I have updated the pull request to use ```resolveUri``` instead.

**Comment by K-Phoen** [comment]
Thanks!

I'd like to test a few things with this PR before merging it. Don't worry if I take a few days to merge this PR, I don't have a lot of free time right now :)

**Comment by MrNicodemuz** [comment]
Bump! :)

**Comment by K-Phoen** [comment]
Sorry for the delay, I quickly tested it but I forgot to merge the PR :(

Thanks for your contribution :+1:

**Pull request merged**
