### PR TITLE
Use asset function in form template

### PR DESCRIPTION
**Pull request by matthieumota**
Be sure link to file is always good if app is in root path or subfolder like preco http://symfony.com/doc/current/templating.html#linking-to-assets

### CODE REVIEW

**Comment by Koc** [comment]
Not sure about it. Download url can be generated by routing

**Comment by garak** [comment]
I'm not sure to understand what "preco" is.
Anyway, what is the path that you can't currently get working using `uri_prefix` option?

**Comment by MatthieuMota** [comment]
Sorry for preco, I mean "recommend". For me, uri_prefix must be relative to base url. Example:
My website production is http://www.startup.com/ and local env is http://localhost/customer/startup/ or http://startup.dev (depends on developer workflow :)). uri_prefix is /uploads/users

In form template from this bundle, download_url return : 
production : http://www.startup.com/uploads/users GOOD
dev 1 :  http://startup.dev/uploads/users GOOD
dev 2 :  http://localhost/uploads/users NOT GOOD but with asset function from twig it transforms to http://localhost/customer/startup/uploads/users

Ok I can redefine download_url in render method from controller but I'm very lazy :)

**Comment by garak** [comment]
It looks like this PR makes sense. As @Koc mentioned, there are some use cases where this is not appropriate, but such cases could be covered by a template override.
In the end, we must choose what is the more general case and cover it with the default template, leaving special cases to custom templates.
My opinion is to favor `asset()`.

**Comment by Koc** [comment]
Oh, now I understand the problem. +1 for `asset` by default if there is easy way to not apply it for some cases (introduce additional option to disable it?)

**Comment by garak** [comment]
We could add another option to `VichFileType`, something like `asset_helper`, to control that.
If we do, the question is again: should we default such option to `false` or `true`? In this case, I'm more inclined for `false`, since is totally BC.

**Comment by Koc** [comment]
lets make it `false` for BC now and change to `true` on 2.0

**Comment by garak** [comment]
@MatthieuMota do you mind to add such configuration to this PR?

**Comment by MatthieuMota** [comment]
@garak Ok I try to see this as soon I've time :)

**Comment by MatthieuMota** [comment]
@garak Need to use 'assets.packages' service from Sf 3 but BC issue. Because it's 'templating.helper.assets' service on Sf2. I don't want to inject the complete service container in form to check if I use one of the two services according to symfony version. I wait your advice for that :)

**Comment by garak** [comment]
I just checked on a project of mine, Symfony 2.8.15, assets.packages is there.

**Comment by Koc** [comment]
for what you need this service directly? you can pass `asset_helper` to template and use it for calling or not calling `asset` function

**Comment by MatthieuMota** [comment]
The service permit to generate the asset url directly without write any logic in the view. But I can pass it to the view if it's ok for you ?

**Comment by garak** [comment]
@MatthieuMota in the meantime we added some indentations, could you please fix conflicts?

**Pull request closed without merging**
