### PR TITLE
[Feature] Enable configuration of db listeners connection

### PR DESCRIPTION
**Pull request by notrix**
This configuration option is a performance update. You may choose witch listener to load for each manager connection.

### CODE REVIEW

**Comment by darceee2** [comment]
:+1:

**Comment by Koc** [comment]
I hope it can be replaced by #617

**Comment by garak** [comment]
@notrix what do you think? Can we close this PR and rely on @koc's one?

**Comment by garak** [comment]
I'm closing this for missing feedback. Feel free to add further comments and/or to open a new PR. Thanks.

**Pull request closed without merging**
