### PR TITLE
Replace form.resources with form_themes key

### PR DESCRIPTION
**Pull request by bocharsky-bw**
The `twig.form.resources` Twig config key is deprecated.

### CODE REVIEW

**Comment by K-Phoen** [comment]
We might want to document both `form.resources` and `form_themes` as this bundle is compatible with Symfony ~2.3 and `form_themes` isn't available before 2.5.

Or we could just skip this section and give a link to the documentation.

What do you think?

**Comment by bocharsky-bw** [comment]
@K-Phoen I think better to show latest available config example in docs.
Also we have link to the official docs, so if someone using an older version of Symfony - he can go to the official docs and see config example for his version. Official Symfony docs have a great versioning until Symfony `2.0`.

So I vote for a new config example with `form_themes` key.

**Comment by K-Phoen** [comment]
Hum. In this case, I'd go for the up-to-date example (`form_themes`) with a note telling users that if they use Symfony < 2.5 they should read [the doc](http://symfony.com/doc/2.3/cookbook/form/form_customization.html#php)

Could look like this:

> **N.B:** the `form_themes` parameter is introduced in Symfony 2.5, check [the documentation](http://symfony.com/doc/2.3/cookbook/form/form_customization.html#php) if you use an older version.

**Comment by bocharsky-bw** [comment]
Yes, you're right.
It would be better with this note
Thanks!

**Comment by K-Phoen** [comment]
Can you add this note in your PR and squash your commits?

I'll merge it once it's done :)

**Comment by bocharsky-bw** [comment]
Ok, I've done

**Comment by K-Phoen** [comment]
Perfect, thanks!

**Pull request merged**
