### PR TITLE
Add doctrine/annotations dependency

### PR DESCRIPTION
**Pull request by Koc**
see
https://github.com/symfony/symfony/pull/20097
https://github.com/symfony/recipes-contrib/pull/22#issuecomment-301831276

### CODE REVIEW

**Comment by harmstyler** [comment]
Is this necessary as a required dependency? Due to the fact that Annotations are optional for this bundle the annotations library should be optional as well. I'd recommend a composer suggestion over a requirement:
```json
"suggest": {
    "doctrine/annotations": "To use Symfony annotations."
}
```

**Comment by garak** [comment]
I agree.
Likely we'll need a line in "require-dev" also

**Comment by Koc** [comment]
Doctrine is a first-class citizen. Adding this dependency as required helps us avoid many missunderstandings and issues in future.

**Comment by garak** [comment]
I think it's just a matter of begin clear in docs.
Even if annotations are suggested in first place, they're not technically a requirement

**Comment by Koc** [comment]
Some parts of DI should be rewrited. Currently annotations are required by code, see https://github.com/symfony/recipes-contrib/pull/22#issuecomment-301831276

**Comment by garak** [comment]
If so, annotations are actually a requirement.

**Pull request merged**
