### PR TITLE
add parent to types

### PR DESCRIPTION
**Pull request by garak**
This should fix the parent issue referred in #401 with compatibility with Symfony 3.
Unfortunately I wasn't able to run tests, since composer doesn't install. I hope everything is fine.

### CODE REVIEW

**Comment by garak** [comment]
Unfortunately, it looks like this is just not working.
Symfony is complaining that you cannot use `add` in `buildForm` without setting `compound` to `true`. Setting `compound` to `true` breaks everything: `The form's view data is expected to be an instance of class Symfony\Component\HttpFoundation\File\File, but is a(n) array`

**Comment by K-Phoen** [comment]
So, does the problem described in #401 really exists and if so, is it blocker?
If it's the case, our two form types might need a bit of refactoring.

WDYT?

**Comment by garak** [comment]
Well, I'm using VichFileType on a situation really similar to the one described in #401 and I never had any problem.
My case is: EntityA in oneToMany with EntityB with cascade persist. EntityB is VichUploadable and its form uses a VichFileType, the form of EntityA is saved without problem

**Comment by Dragnucs** [comment]
@garak I am using this bundle with Symfony 3.0.3, Installed with provided documentation and it is working fine. I cannot reproduce your problem.

**Comment by K-Phoen** [comment]
Given that there is no other report of this issue, I think we can ignore it and release 1.0.0 today :)

**Comment by garak** [comment]
Great! I'm closing this

**Pull request closed without merging**
