### PR TITLE
Fix Type: getUploadDir could not be null

### PR DESCRIPTION
**Pull request by RobinDev**

### CODE REVIEW

**Review by garak — CHANGES_REQUESTED** [review]
I don't get the reason for this change. Even if there's one, CI is failing

**Comment by RobinDev** [comment]
Reason : avoid to have to ignore the static analysis error or to do a useless string cast.

Normally, I fix the CI and if you think this pr is useless, it's okay for closing it.

**Comment by garak** [comment]
bump

**Comment by garak** [comment]
I'm sorry but I have to close this, it's too old and has no feedback.

**Pull request closed without merging**
