### PR TITLE
Added possibility store file info #413, #534

### LINKED ISSUE #413: Merge functionality from IphpFileStoreBundle
Have a look at https://github.com/vitiko/IphpFileStoreBundle .

I implemented that bundle first, but I like the way VichUploaderBundle handles the entity by using Symfony\Component\HttpFoundation\File\File better. There is some functionality thought that I appreciated:

- Annotated field data, the field in the database contains an array with usefull information:
 - path — full path to file in web dir, including web path to upload dir
 - size — file size in bytes
 - fileName — path to file , relative to web path of upload dir
 - originalName — original file name before upload
 - mimeType — file mime type
 - width — image width
 - height — image height
- File Namers
 - Transliteration - replace cyrillic and other chars to ascii
 - File name by value of entity field ( eg. the id)
- Directory Namers
 - Create subdirectory by date
 - Using entity field value
 - Using entity field name
 - Using entity class name

The best one, I think, is the array in the database which makes it possible to get back the original name when using a unique file namer.

Could these be implemented?

### PR DESCRIPTION
**Pull request by Koc**
Fixes #413, #534

- [x] Add new tests
- [x] Update documentation

### CODE REVIEW

**Comment by garak** [comment]
I see that related issues are closed, is this PR still relevant?

**Comment by Koc** [comment]
@garak yes, this is useful to have this feature in the core and not reimplement listeners for each project that needed file info

**Comment by garak** [comment]
What about "[WIP]" annotation? Is this still a work in progress, or is it ready to merge?

**Comment by Koc** [comment]
I need do rebase and add new tests. Will do it next week

**Comment by Koc** [comment]
@garak I've rebased PR, added new tests, but haven't yet checked that this works in general.

**Comment by Koc** [comment]
oh no, we need rebase again(

**Comment by Koc** [comment]
Almost ready. Found and fixed a bug in annotation driver, but need add test that covers it.

**Comment by Koc** [comment]
@garak ready to review and merge

**Pull request merged**
