### PR TITLE
Add translation for label

### PR DESCRIPTION
**Pull request by pierre-H**

### CODE REVIEW

**Comment by garak** [comment]
Hey @pierre-H, thanks for your contribution.
Can you add a little rationale to this PR?

**Comment by pierre-H** [comment]
Yes
It's useful when you do this : 
```php
$builder->add('file', VichUploadType::class, ['label' => 'app.product_file']
```

And then displaying the `app.product_file` translation and not the string 'app.product_file'.

**Comment by pierre-H** [comment]
Wait … Don't push that … I've got a better implementation ...

**Comment by garak** [comment]
thank you!

**Pull request merged**
