### PR TITLE
also check Resources/config/vich_uploader for mapping configuration

### PR DESCRIPTION
**Pull request by zghosts**
Fixes the BC break in as reported in issue #1067 by also checking Resources/config/vich_uploader if ../config/vich_uploader is not found

### CODE REVIEW

**Comment by zghosts** [comment]
I'll update the readme.md and upgrade.md accordingly

**Comment by garak** [comment]
I'm also thinking that it would be nice to add a deprecated message for the old path.
We'll remove it in 2.0

**Comment by zghosts** [comment]
While that would be the way to go in order to remove support for it, as the documented directory layout for a bundle still recommends Resources/config I personally think you should hold off on removing support for it.

**Comment by garak** [comment]
As already mentioned, documentation is just outdated.
Anyway, we still don't have a date for version 2 release, so it will be in the far future.

**Comment by zghosts** [comment]
I'll add a deprecation notice aswell then

**Comment by zghosts** [comment]
That means changing the layout of TestBundle in tests/Fixtures right?
Or actually creating a second test bundle with the new layout applied so both can be tested

**Comment by garak** [comment]
Right, so let's drop the legacy test. Just change current TestBundle

**Comment by zghosts** [comment]
I was reading up on the current state of the new layout deprecation.
quoting the changelog for 4.4/5.0
"As many bundles must be compatible with a range of Symfony versions, the current directory convention is not deprecated yet, but it will be in the future."

How about not triggering a deprecation until symfony deprecates the old layout.
But changing the test fixture to support the new layout.

**Comment by garak** [comment]
This is mainly intended for project configuration.
Using a bundle (like AppBundle) for projects is deprecated since ages and I don't see a reason to avoid deprecation on our side

**Pull request merged**
