### PR TITLE
downloadhandler fix for non-ascii file name

### PR DESCRIPTION
**Pull request by tgabi333**
Response dispositions must have ASCII file names

### CODE REVIEW

**Comment by tgabi333** [comment]
@K-Phoen what do you think of it?

**Comment by K-Phoen** [comment]
I'll review this PR tonight or during the week-end :)

**Comment by tgabi333** [comment]
Thank you very much :)

**Comment by K-Phoen** [comment]
A fix for that landed in master, thanks for your time/PR and sorry for the delay!

**Pull request closed without merging**
