### PR TITLE
Make docs more clear.

### PR DESCRIPTION
**Pull request by marcharding**
Make it clear to use the VichFileType  and not the native Symfony FileType.

### CODE REVIEW

**Comment by garak** [comment]
Why not `VichImageType`?

**Comment by marcharding** [comment]
Yes, even better 😉 

The docs are a bit confusing in this regard, i still had the native symfony file type in my form and wondered why it did not work. I suppose that could happen to others as well..

**Comment by garak** [comment]
Can you update your PR?

**Comment by garak** [comment]
Thank you @marcharding !

**Pull request merged**
